### ISSUE TITLE
Transformer & filter models

### ISSUE THREAD

**Issue by hakanergun** [Electa-Git/PowerModelsACDC.jl#1]
Transformer, filter and reactor losses need to be added

**Comment by frederikgeth** [comment]
added in b2815f2bc46cfe853ed7644bfbeaf1f0e0b8c645 for all formulations
to be tested further.

also included, a setting to ignore impedance values for transformer and phase reactor below a certain threshold, through `setting = Dict("zthresh" => 0.0001)`

**Comment by hakanergun** [comment]
I think instead of ztthresh, it sshould be a binary parameter to include the components.

**Comment by ccoffrin** [comment]
I think a binary parameter is a better long term solution as well.

**Comment by hakanergun** [comment]
Binaries implemented (similar to the version before with if cases). It would be possible to add the constraints as sums using the binaries to make all the distinctions, nevertheless that's not handy because the constraint change from linear to non-linear (even if the binary of NL constraint is 0).
