### ISSUE TITLE
remove matlab-style dc line model

### ISSUE THREAD

**Issue by frederikgeth** [Electa-Git/PowerModelsACDC.jl#8]
reparameterize a MATPOWER-style dc line automatically by converting it to two a line with a converter at both ends.

**Comment by hakanergun** [comment]
That is not that straightforward because of the weird loss model of matpower, where the Pl_tot = Pfr - Pto. So I suppose it is better not to support it, as it is a really strange way of defining losses / flow...

**Comment by frederikgeth** [comment]
consistent transformation is only defined for DCPPowerModel, not for AC

**Comment by frederikgeth** [comment]
closed by 15a8a84235c8ba327ee70fc3ffef68991e7bc42b
